In [1]:
import pylearn2.utils
import pylearn2.config

Using gpu device 1: Tesla K40c


In [3]:
cd .. 

/afs/inf.ed.ac.uk/user/s13/s1320903/Neuroglycerin/neukrill-net-work


In [4]:
model = pylearn2.utils.serial.load('y_pickle')

In [6]:
len(model)

6052

In [7]:
model[1,:]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1])

In [8]:
model[2,:]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1])

In [11]:
model[0,:]

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1])

In [13]:
all(model[0,:] == model[1,:])

True

In [14]:
model.shape

(6052, 188)

In [18]:
import neukrill_net.utils as utils
settings = neukrill_net.utils.Settings("settings.json")
validation_set = utils.train_test_split(settings.image_fnames, "validation", train_split=0.8)

In [24]:
validation_set

{u'acantharia_protist': [u'/disk/scratch/neuroglycerin/train/acantharia_protist/72486.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/72538.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/72640.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/72655.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/72726.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/72729.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/73207.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/73425.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/73440.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/73514.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/73949.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/74054.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/74148.jpg',
  u'/disk/scratch/neuroglycerin/train/acantharia_protist/74224.jpg',
  u'/disk/s

In [27]:
len(validation_set['acantharia_protist'])

89

In [34]:
for i in range(178):
    print(all(model[i,:] == model[i+1,:]))

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False


In [36]:
all(model[178,:] == model[179,:])

True

In [129]:
lengths = []
for key in settings.classes:
    lengths.append(len(validation_set[key]))
print(lengths)

indices = []

begin = 0
for l in range(len(lengths)):
    end = begin + 2*lengths[l]
    print(begin)
    print(end)
    array = model[begin:end, :]
    if ((array - array[0]) == 0).all():
        print(True)
    else:
        indices.append((begin, end, l))    
    begin = end

[89, 1, 7, 5, 2, 53, 70, 24, 39, 17, 81, 193, 69, 8, 68, 17, 10, 18, 6, 29, 11, 5, 9, 3, 90, 119, 2, 20, 11, 4, 5, 4, 5, 36, 39, 91, 52, 50, 4, 9, 8, 9, 38, 54, 10, 3, 1, 14, 4, 51, 1, 3, 8, 11, 6, 2, 1, 13, 7, 3, 23, 1, 2, 2, 13, 34, 1, 19, 41, 27, 15, 8, 70, 12, 4, 6, 1, 6, 1, 2, 14, 13, 11, 37, 62, 117, 11, 11, 1, 6, 29, 16, 5, 5, 15, 17, 21, 13, 48, 18, 6, 25, 3, 3, 13, 2, 2, 4, 71, 5, 198, 68, 3, 44, 42, 35, 24, 7, 32, 17, 42]
0
178
True
178
180
True
180
194
True
194
204
True
204
208
True
208
314
True
314
454
True
454
502
True
502
580
True
580
614
True
614
776
True
776
1162
True
1162
1300
True
1300
1316
True
1316
1452
True
1452
1486
True
1486
1506
True
1506
1542
True
1542
1554
True
1554
1612
True
1612
1634
True
1634
1644
True
1644
1662
True
1662
1668
True
1668
1848
True
1848
2086
True
2086
2090
True
2090
2130
True
2130
2152
True
2152
2160
True
2160
2170
True
2170
2178
True
2178
2188
True
2188
2260
True
2260
2338
True
2338
2520
True
2520
2624
True
2624
2724
True
2724
2732
True
2732

In [131]:
indices

[]

In [112]:
import numpy
numpy.where((model[208:348, :]- model[208, :]) != 0)

(array([106, 106, 107, 107, 108, 108, 109, 109, 110, 110, 111, 111, 112,
        112, 113, 113, 114, 114, 115, 115, 116, 116, 117, 117, 118, 118,
        119, 119, 120, 120, 121, 121, 122, 122, 123, 123, 124, 124, 125,
        125, 126, 126, 127, 127, 128, 128, 129, 129, 130, 130, 131, 131,
        132, 132, 133, 133, 134, 134, 135, 135, 136, 136, 137, 137, 138,
        138, 139, 139]),
 array([5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5,
        6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6,
        5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6]))

In [115]:
sorted(validation_set)[5]

u'appendicularian_s_shape'

In [126]:
numpy.where((model[3300:3368, :]- model[3300, :]) != 0)

(array([26, 26, 27, 27, 28, 28, 29, 29, 30, 30, 31, 31, 32, 32, 33, 33, 34,
        34, 35, 35, 36, 36, 37, 37, 38, 38, 39, 39, 40, 40, 41, 41, 42, 42,
        43, 43, 44, 44, 45, 45, 46, 46, 47, 47, 48, 48, 49, 49, 50, 50, 51,
        51, 52, 52, 53, 53, 54, 54, 55, 55, 56, 56, 57, 57, 58, 58, 59, 59,
        60, 60, 61, 61, 62, 62, 63, 63, 64, 64, 65, 65, 66, 66, 67, 67]),
 array([64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64,
        65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65,
        64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64,
        65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65,
        64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65, 64, 65]))

In [128]:
settings.classes == sorted(validation_set)

False

In [132]:
for i,j in zip(settings.classes, sorted(validation_set)):
    if i != j:
        print(i,j)

(u'appendicularian_slight_curve', u'appendicularian_s_shape')
(u'appendicularian_s_shape', u'appendicularian_slight_curve')
(u'hydromedusae_narcomedusae', u'hydromedusae_narco_young')
(u'hydromedusae_narco_young', u'hydromedusae_narcomedusae')
(u'shrimp_caridean', u'shrimp-like_other')
(u'shrimp-like_other', u'shrimp_caridean')
